### ISSUE TITLE
Bug from #15

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/USFM-Tools#16]
I think #15 caused this:

```
python /var/www/vhosts/door43.org/USFM-Tools/transform.py --target=usx --usfmDir=/var/www/vhosts/api.unfoldingword.org/httpdocs/ulb/txt/1/ulb-en/ --builtDir=/tmp/ulb/ --fileByBook
Traceback (most recent call last):
  File "/var/www/vhosts/door43.org/USFM-Tools/transform.py", line 12, in <module>
    import readerise
  File "/var/www/vhosts/door43.org/USFM-Tools/support/readerise.py", line 5, in <module>
    import parseUsfm
  File "/var/www/vhosts/door43.org/USFM-Tools/support/parseUsfm.py", line 53, in <module>
    cl      = usfmToken(u"cl", phrase)
TypeError: usfmToken() takes exactly 1 argument (2 given)
```

**Comment by da1nerd** [comment]
not sure what you mean. issue #15 was me accidentally placing a copy of #14 in this repo when re-assigning.

**Comment by jag3773** [comment]
Ah, in that case it was #13.  I ran an update on the server's repo and got updates, which I thought were from #15 but I guess it was actually code from #13.

**Comment by da1nerd** [comment]
noted. Thanks.
