### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/USFM-Tools#5]
While processing https://github.com/unfoldingWord/udb-en/blob/master/01-GEN-en-UDB.usfm, I get:

``` (GEN)
     Error: After GENESIS 14:18 - Unknown Token: \v
     (GEN)
     Error: After GENESIS 14:18 - Unknown Token: \v
Traceback (most recent call last):
  File "transform.py", line 227, in <module>
    main(sys.argv[1:])
  File "transform.py", line 207, in main
    buildUSX(usfmDir, buildDir, buildName, byBookFlag)
  File "transform.py", line 137, in buildUSX
    c.render()
  File "/var/www/vhosts/door43.org/USFM-Tools/support/usxRenderer.py", line 36, in render
    self.run()
  File "/var/www/vhosts/door43.org/USFM-Tools/support/abstractRenderer.py", line 30, in run
    for t in tokens: t.renderOn(self)
  File "/var/www/vhosts/door43.org/USFM-Tools/support/parseUsfm.py", line 638, in renderOn
    return printer.renderLI(self)
  File "/var/www/vhosts/door43.org/USFM-Tools/support/usxRenderer.py", line 127, in renderLI
    def renderLI(self, token):      self.f.write( self.stopP() + self.stopQ() + self.stopLI() + self.startLI() )
TypeError: startLI() takes exactly 2 arguments (1 given)
```

Note that I don't see the problematic "\v" token after Gen 14:18 either.

**Comment by jag3773** [comment]
Note this is an error in processing \li items, see https://github.com/unfoldingWord/udb-en/blob/master/01-GEN-en-UDB.usfm#L3184.

**Comment by da1nerd** [comment]
Looks like it is on 14:1

There is no space between the first number and the actual verse text. 

I've noticed the error report is sometimes off by a few verses. 

—
